### ISSUE TITLE
[feature request] Display installed apps first

### ISSUE THREAD

**Issue by asamofal** [revancedapps/revancedmanager#1]
Hi there! Thanks for providing such a great tool! 

It would be nice if the apps list could be split based on the criteria of installed and not installed, with the installed apps displayed first. I frequently open the manager to check for updates, but it's uncomfortable to scroll through the entire list every time to check each of my installed apps.

By the way: do you plan any push notifications about new available or installed updates? I like to know about such events...

**Comment by revancedapps** [comment]
Thank you for suggesting the arrangement of apps in order of priority, displaying the pre-installed ones first. This feature will be applied in the new version, which will be released in a few minutes. 

Creating notifications is already in my plan, but it wasn't included in this update. I will update it when I have more time.
