### ISSUE TITLE
MicroG background message keeps on showing 

### ISSUE THREAD

**Issue by yasinULLAH** [revancedapps/revancedmanager#11]
The old microG was working fine even without battery optimization on 😢... The  new one revanced keep on crashing with the message "MicroG in not running in background" even though I have turned off battery optimization for MicroG please fix this also the new version is more battery aggressive rather the old one.

**Comment by revancedapps** [comment]
It all started with this issue [#2958](https://github.com/ReVanced/revanced-patches/pull/2958) , then oSumAtrIX added a piece of code to force the background running of microG. I also find this notification a bit annoying, but it will fix the error where the video stops after running for 1-2 minutes.
