### ISSUE TITLE
Why the apps in the website are not in the manager ?

### ISSUE THREAD

**Issue by soulnous** [revancedapps/revancedmanager#17]
Hey 

Why the apps in the website are not in the manager ?
You uploaded yesterday new YouTube versions but they are now in the revanced manager app , why ? Thx !

**Comment by revancedapps** [comment]
Hi, thank for the feedback. I have just added them via changeset [#9e9cf11](https://github.com/revancedapps/revancedmanager/commit/9e9cf11de7801e45c50d817c400792127c42e412)
