### ISSUE TITLE
Auto update option

### ISSUE THREAD

**Issue by GKid94** [revancedapps/revancedmanager#21]
Can you please add a auto update apps option in the manager?

**Comment by revancedapps** [comment]
I can do this task, but it requires the app to run in the background to check for updates. I want Revanced Manager to run as smoothly as possible. To avoid any unnecessary doubts and questions, I didn't add this feature yet. 
However, your suggestion makes a lot of sense. In future updates, I will add a button like "one-click update all apps" and "new version notification" to simplify the update steps.
Thanks
