### ISSUE TITLE
Downloading videos for offline use

### ISSUE THREAD

**Issue by yasinULLAH** [revancedapps/revancedmanager#26]
Can't download videos for offline use it even goes up to a certain point like 10 or 20 percent then freezes or sometime it freeze even from the beginning tried everything nothing working . It sometimes even works goes as slow as hell 2mb per half hour at internet speed of 40mbps

**Comment by revancedapps** [comment]
It seems that this function is experiencing issues. In the meantime, please try using external apps like YTDLnis or PC applications like yt-dlp.
