### ISSUE TITLE
Revanced Manager tries to refresh and all the apps disappear

### ISSUE THREAD

**Issue by Tito151** [revancedapps/revancedmanager#27]
The only thing that'll show is three blue buttons for donations; the website and the source code (to here). I've tried removing Revanced Manager and GMS Core, installing their latest versions from the website and making sure that my ad blocker is whitelisting the apps and trying it again with the ad blocker turned off. Still, the apps appear for a second (and I can click one if I'm fast) and then all disappear.
![Screenshot (Dec 13, 2024 9_23_18 PM)](https://github.com/user-attachments/assets/d5d73a38-edf6-46c5-9d74-8a0288ba503b)

**Comment by revancedapps** [comment]
This is a bug in version 2.0.5 where I encountered an issue in the code while parsing JSON to retrieve version information and the list of the latest apps. Simply visit the homepage to download the latest version of ReVanced Manager, and this bug will be fixed.
