### ISSUE TITLE
Youtube Music 

### ISSUE THREAD

**Issue by howdy-rowdy** [revancedapps/revancedmanager#29]
Youtube music with mobile data takes forever to play even just one song! I use Jio sim and this is happening to me only in Yt music, app working fine with wifi though. But I don't have wifi outdoors :(
Edit: in the meantime tried rvx yt music extended, app is working perfectly fine:)
![Screenshot_20241214_121920](https://github.com/user-attachments/assets/60101d5e-f3f7-461a-9a7d-34f0b05a37d8)

**Comment by howdy-rowdy** [comment]
Edit: in the meantime tried rvx yt music extended, app is working perfectly fine :)

**Comment by WenLonG12345** [comment]
Hi, I having the same problem too, is it Youtube starting to block all those unauthorised traffic?

**Comment by howdy-rowdy** [comment]
I don't think so

**Comment by revancedapps** [comment]
My experience includes using latestversion of both ReVanced YouTube Music and ReVanced Extended YouTube Music. Indeed, since April, Google has gradually made some changes that have caused third-party YouTube apps to run inconsistently, and sometimes YouTube Music experiences the same issues.
