### ISSUE TITLE
App empty?

### ISSUE THREAD

**Issue by queermeet-dev** [revancedapps/revancedmanager#31]
I installed the app and when I opened it a few days later, it was empty

Then I reinstalled it, everything worked and now empty again:

![Screenshot_2024-12-16-23-21-53-270_com.revanced.net.revancedmanager.jpg](https://github.com/user-attachments/assets/3079426e-6c5c-4572-a2e3-d7a59fed183e)

**Comment by revancedapps** [comment]
This is a bug in version 2.0.5 where I encountered an issue in the code while parsing JSON to retrieve version information and the list of the latest apps. Simply visit the homepage to download the latest version of ReVanced Manager from https://revanced.net/revanced-manager#download-apk , and this bug will be fixed.

**Comment by queermeet-dev** [comment]
Thanks
