### ISSUE TITLE
Not working, I think it went down.. 

### ISSUE THREAD

**Issue by MarshMeadow** [revancedapps/revancedmanager#36]
Not loading, blank, can't use.. ![Screenshot_20241224_174038_ReVanced Manager.jpg](https://github.com/user-attachments/assets/2a837da2-aee4-454a-af44-901802bb51e7)

**Comment by revancedapps** [comment]
This is a bug in version 2.0.5 where I encountered an issue in the code while parsing JSON to retrieve version information and the list of the latest apps. Simply visit the homepage to download the latest version of ReVanced Manager from https://revanced.net/revanced-manager#download-apk , and this bug will be fixed.

**Comment by xenithorb** [comment]
Still seeing this in 2.09 even after clearing data

**Comment by di57inct** [comment]
https://github.com/revancedapps/revancedmanager/issues/33#issuecomment-2592658144
