### ISSUE TITLE
unable to assecc to the normal download page of revanced manager

### ISSUE THREAD

**Issue by john371911** [revancedapps/revancedmanager#38]
My device is ZenFone 9, android 14. When I tap revanced manager, it only shows the screen instead of normal download, update page.
![Screenshot_20241228-221122_ReVanced_Manager](https://github.com/user-attachments/assets/1e7f2ea9-a04f-4ee4-a6b5-2ed53b424e7b)

**Comment by revancedapps** [comment]
This is a bug in version 2.0.5 where I encountered an issue in the code while parsing JSON to retrieve version information and the list of the latest apps. Simply visit the homepage to download the latest version of ReVanced Manager from https://revanced.net/revanced-manager#download-apk , and this bug will be fixed.

**Comment by di57inct** [comment]
https://github.com/revancedapps/revancedmanager/issues/33#issuecomment-2592658144
