### ISSUE TITLE
No support for Anroid 6.0 & 7.0 apps

### ISSUE THREAD

**Issue by Rushikesh-Malave-175** [revancedapps/revancedmanager#4]
I love you guys, and the work you're doing. Helps a ton for non-tech people like my sister.
Please add support for android 6.0 and android 7.0 apps. At least for YouTube and YouTube music.
Also add support for other architecture. I have Android 6.0, arm-v7 device. Your precompiled YouTube doesn't install.

**Comment by revancedapps** [comment]
Hi, thank you for your suggestion. 
Currently, we only support YouTube versions available on ApkMirror (which I believe is the most reliable and clean source), so there are some limitations regarding the Android API level and AP architecture. I will consider this request and will add other architectures when I find a more stable source.
