### ISSUE TITLE
YouTube history not working in the extended app

### ISSUE THREAD

**Issue by yasinULLAH** [revancedapps/revancedmanager#7]
Revanced YouTube premium is fixed (the one with the red original YouTube icon) **but revanced extended YouTube is till not fixed**

**Comment by revancedapps** [comment]
Hi, currently, the Revanced Extended (RVX) repository of developer inotia00 has been not updated since Jan 27, 2024, and it seems to be no longer maintained. 
I think we might consider gradually transitioning to the mainstream of **Revanced YouTube** so that we can get updates and bug fixes.

**Comment by yasinULLAH** [comment]
I wanted and needed to use both of them... And also Revanced YouTube has no playback speed layout icon like the extended one

**Comment by revancedapps** [comment]
Alright, the latest version of Youtube Revanced Extended v19.05.36 has been released. It addresses the issue with watch history. You can download it from [revanced.net](https://revanced.net) or by using the Revanced.Net Manager tool.
https://revanced.net/revanced-youtube-extended
